build:
    tests:
        override:
                 - ./run-tests.sh


checks:
    php:
        code_rating: true
        duplication: true
    filter:
        excluded_paths:
            - src/*
            - tests/*