language: php

dist: precise

matrix:
  fast_finish: true

php:
  - 5.6
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover --debug

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="66f52a8423a65504a32da603eb3f498034866b9d10071cccc9e2c58424413edf" --format=php-clover coverage.clover