language: php

dist: precise

matrix:
  fast_finish: true

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retray apt-get install php-pear
  - travis_retray  pear channel-update pear.php.net
  - travis_retray  pear upgrade-all
  - travis_retray  pear channel-discover pear.phpunit.de
  - travis_retray  pear install -a phpunit/PHPUnit

script:
  - mkdir -p build/logs
  - phpunit -v