language: php

php:
  - 5.6
  #- 7.1

services:
  - mysql

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
 # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
      psql --version
      mysql --version
    fi
  # initialize databases
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
    fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  # - travis_retry vendor/bin/yii migrate
  # enable code coverage
   - |
     if [ $TASK_TESTS_COVERAGE == 1 ]; then
       PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
     fi


script:
  #- phpunit --verbose $PHPUNIT_FLAGS
  -  vendor/bin/phpunit tests --bootstrap ./tests/bootstrap.php  LookupTest

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
