language: php

dist: precise

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --debug

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover