language: php

dist: precise

matrix:
  fast_finish: true

php:
  - 5.6


install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --debug