language: php

matrix:
  fast_finish: true

php:
  - 7.1

  # cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover