language: php

php:
  - 5.6
  #- 7.1
# faster builds on new travis setup not using sudo
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover